
test:
  image: python:3.7-buster
  stage: test
  before_script:
#  - apt install git
#  - pip install git+https://github.com/AllenInstitute/asap-modules
#  - pip install git+https://git.embl.de/schorb/pyem
#  - pip install git+https://github.com/constantinpape/pybdv
#  - pip install -r requirements.txt
#  - pip install -r test_requirements.txt
  script:
  - useradd testuser
  - mkdir test123
  - su testuser -c "whoami && pwd && ls && coverage run -m pytest"
  - coverage xml
  artifacts:
    reports:
      cobertura:
        coverage.xml
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    
pages:
  image: python:3.7-buster
  stage: deploy
  before_script:
  - apt install git
  - pip install -U sphinx
  - pip install git+https://github.com/AllenInstitute/asap-modules
  - pip install git+https://git.embl.de/schorb/pyem
  - pip install git+https://github.com/constantinpape/pybdv
  - pip install -r requirements.txt
  script:
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - main
  - doctest