dockertest:
  image: docker:20-git
  stage: test
  script:
    - docker run -v /var/run/docker.sock:/var/run/docker.sock \
      -ti docker


#
#test:
#  image: python:3.7-buster
#  stage: test
#  before_script:
#  - apt install git
#  - pip install git+https://github.com/AllenInstitute/asap-modules
#  - pip install git+https://git.embl.de/schorb/pyem
#  - pip install git+https://github.com/constantinpape/pybdv
#  - pip install -r requirements.txt
#  - pip install -r test_requirements.txt
#  script:
#  - useradd testuser
#  - chmod 777 -R *
#  - su testuser -c "coverage run -m pytest"
#  - coverage xml
#  - coverage-badge
#  - coverage report
#  artifacts:
#    reports:
#      cobertura:
#        coverage.xml
#  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    
pages:
  image: python:3.7-buster
  stage: deploy
  before_script:
  - apt install git
  - pip install -U sphinx
  - pip install git+https://github.com/AllenInstitute/asap-modules
  - pip install git+https://git.embl.de/schorb/pyem
  - pip install git+https://github.com/constantinpape/pybdv
  - pip install -r requirements.txt
  script:
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - main
  - doctest